
CREATE TABLE TB_SYSTEM_ENGINE
(
	ENGINE_ID            VARCHAR2(20) NOT NULL ,
	ENGINE_NM            VARCHAR2(45) NULL ,
	SERVER_ID            VARCHAR2(20) NOT NULL ,
	API_PORT_NB          NUMBER NOT NULL ,
	MIN_MEMORY_MB        NUMBER NOT NULL ,
	MAX_MEMORY_MB        NUMBER NOT NULL ,
	EXE_FILE_PATH        VARCHAR2(500) NOT NULL ,
	START_DT             DATE NULL ,
	END_DT               DATE NULL ,
	DEL_FG               CHAR(1) DEFAULT  'N'  NOT NULL ,
	REG_FST_DT           DATE DEFAULT  SYSDATE  NOT NULL ,
	UPT_LAST_DT          DATE DEFAULT  SYSDATE  NOT NULL 
);



CREATE UNIQUE INDEX PK_SYSTEM_ENGINE ON TB_SYSTEM_ENGINE
(ENGINE_ID   ASC);



ALTER TABLE TB_SYSTEM_ENGINE
	ADD CONSTRAINT  PK_SYSTEM_ENGINE PRIMARY KEY (ENGINE_ID);



CREATE TABLE TB_SYSTEM_ENGINE_CONFIG
(
	ENGINE_ID            VARCHAR2(20) NOT NULL ,
	CONFIG_KEY           VARCHAR2(100) NOT NULL ,
	CONFIG_VALUE         VARCHAR2(300) NULL ,
	EXPLAIN_DS           VARCHAR2(500) NULL ,
	DEL_FG               CHAR(1) DEFAULT  'N'  NOT NULL ,
	REG_FST_DT           DATE DEFAULT  SYSDATE  NOT NULL ,
	UPT_LAST_DT          DATE DEFAULT  SYSDATE  NOT NULL 
);



CREATE UNIQUE INDEX PK_SYSTEM_ENGINE_CONFIG ON TB_SYSTEM_ENGINE_CONFIG
(ENGINE_ID   ASC,CONFIG_KEY   ASC);



ALTER TABLE TB_SYSTEM_ENGINE_CONFIG
	ADD CONSTRAINT  PK_SYSTEM_ENGINE_CONFIG PRIMARY KEY (ENGINE_ID,CONFIG_KEY);



CREATE TABLE TB_SYSTEM_SERVER
(
	SERVER_ID            VARCHAR2(20) NOT NULL ,
	SERVER_NM            VARCHAR2(45) NULL ,
	HOST_ADDR            VARCHAR2(50) NOT NULL ,
	API_PORT_NB          NUMBER NOT NULL ,
	OS_TP                VARCHAR2(10) DEFAULT  'UNIX'  NOT NULL ,
	START_DT             DATE NULL ,
	END_DT               DATE NULL ,
	DEL_FG               CHAR(1) DEFAULT  'N'  NOT NULL ,
	REG_FST_DT           DATE DEFAULT  SYSDATE  NOT NULL ,
	UPT_LAST_DT          DATE DEFAULT  SYSDATE  NOT NULL 
);



CREATE UNIQUE INDEX PK_SYSTEM_SERVER ON TB_SYSTEM_SERVER
(SERVER_ID   ASC);



ALTER TABLE TB_SYSTEM_SERVER
	ADD CONSTRAINT  PK_SYSTEM_SERVER PRIMARY KEY (SERVER_ID);



CREATE TABLE TB_SYSTEM_SERVER_CONFIG
(
	SERVER_ID            VARCHAR2(20) NOT NULL ,
	CONFIG_KEY           VARCHAR2(100) NOT NULL ,
	CONFIG_VALUE         VARCHAR2(300) NULL ,
	EXPLAIN_DS           VARCHAR2(500) NULL ,
	DEL_FG               CHAR(1) DEFAULT  'N'  NOT NULL ,
	REG_FST_DT           DATE DEFAULT  SYSDATE  NOT NULL ,
	UPT_LAST_DT          DATE DEFAULT  SYSDATE  NOT NULL 
);



CREATE UNIQUE INDEX PK_SYSTEM_SERVER_CONFIG ON TB_SYSTEM_SERVER_CONFIG
(SERVER_ID   ASC,CONFIG_KEY   ASC);



ALTER TABLE TB_SYSTEM_SERVER_CONFIG
	ADD CONSTRAINT  PK_SYSTEM_SERVER_CONFIG PRIMARY KEY (SERVER_ID,CONFIG_KEY);



ALTER TABLE TB_SYSTEM_ENGINE
	ADD (CONSTRAINT R_18 FOREIGN KEY (SERVER_ID) REFERENCES TB_SYSTEM_SERVER (SERVER_ID) ON DELETE SET NULL);



ALTER TABLE TB_SYSTEM_ENGINE_CONFIG
	ADD (CONSTRAINT R_19 FOREIGN KEY (ENGINE_ID) REFERENCES TB_SYSTEM_ENGINE (ENGINE_ID));



ALTER TABLE TB_SYSTEM_SERVER_CONFIG
	ADD (CONSTRAINT R_16 FOREIGN KEY (SERVER_ID) REFERENCES TB_SYSTEM_SERVER (SERVER_ID));



COMMENT ON TABLE TB_SYSTEM_ENGINE IS '[시스템]엔진'; 
        COMMENT ON COLUMN TB_SYSTEM_ENGINE.ENGINE_ID IS '엔진아이디'; 
         COMMENT ON COLUMN TB_SYSTEM_ENGINE.ENGINE_NM IS '엔진명'; 
         COMMENT ON COLUMN TB_SYSTEM_ENGINE.SERVER_ID IS '서버아이디'; 
         COMMENT ON COLUMN TB_SYSTEM_ENGINE.API_PORT_NB IS 'Api포트번호'; 
         COMMENT ON COLUMN TB_SYSTEM_ENGINE.MIN_MEMORY_MB IS '최소메모리'; 
         COMMENT ON COLUMN TB_SYSTEM_ENGINE.MAX_MEMORY_MB IS '최대메모리'; 
         COMMENT ON COLUMN TB_SYSTEM_ENGINE.EXE_FILE_PATH IS '실행파일경로'; 
         COMMENT ON COLUMN TB_SYSTEM_ENGINE.START_DT IS '시작일시'; 
         COMMENT ON COLUMN TB_SYSTEM_ENGINE.END_DT IS '종료일시'; 
         COMMENT ON COLUMN TB_SYSTEM_ENGINE.DEL_FG IS '삭제여부'; 
         COMMENT ON COLUMN TB_SYSTEM_ENGINE.REG_FST_DT IS '최초등록일시'; 
         COMMENT ON COLUMN TB_SYSTEM_ENGINE.UPT_LAST_DT IS '최종수정일시'; 
          
COMMENT ON TABLE TB_SYSTEM_ENGINE_CONFIG IS '[시스템]엔진설정'; 
        COMMENT ON COLUMN TB_SYSTEM_ENGINE_CONFIG.ENGINE_ID IS '엔진아이디'; 
         COMMENT ON COLUMN TB_SYSTEM_ENGINE_CONFIG.CONFIG_KEY IS '설정키'; 
         COMMENT ON COLUMN TB_SYSTEM_ENGINE_CONFIG.CONFIG_VALUE IS '설정값'; 
         COMMENT ON COLUMN TB_SYSTEM_ENGINE_CONFIG.EXPLAIN_DS IS '설명서술'; 
         COMMENT ON COLUMN TB_SYSTEM_ENGINE_CONFIG.DEL_FG IS '삭제여부'; 
         COMMENT ON COLUMN TB_SYSTEM_ENGINE_CONFIG.REG_FST_DT IS '최초등록일시'; 
         COMMENT ON COLUMN TB_SYSTEM_ENGINE_CONFIG.UPT_LAST_DT IS '최종수정일시'; 
          
COMMENT ON TABLE TB_SYSTEM_SERVER IS '[시스템]서버'; 
        COMMENT ON COLUMN TB_SYSTEM_SERVER.SERVER_ID IS '서버아이디'; 
         COMMENT ON COLUMN TB_SYSTEM_SERVER.SERVER_NM IS '서버명'; 
         COMMENT ON COLUMN TB_SYSTEM_SERVER.HOST_ADDR IS '호스트주소'; 
         COMMENT ON COLUMN TB_SYSTEM_SERVER.API_PORT_NB IS 'Api포트번호'; 
         COMMENT ON COLUMN TB_SYSTEM_SERVER.OS_TP IS '운영체제유형'; 
         COMMENT ON COLUMN TB_SYSTEM_SERVER.START_DT IS '시작일시'; 
         COMMENT ON COLUMN TB_SYSTEM_SERVER.END_DT IS '종료일시'; 
         COMMENT ON COLUMN TB_SYSTEM_SERVER.DEL_FG IS '삭제여부'; 
         COMMENT ON COLUMN TB_SYSTEM_SERVER.REG_FST_DT IS '최초등록일시'; 
         COMMENT ON COLUMN TB_SYSTEM_SERVER.UPT_LAST_DT IS '최종수정일시'; 
          
COMMENT ON TABLE TB_SYSTEM_SERVER_CONFIG IS '[시스템]서버설정'; 
        COMMENT ON COLUMN TB_SYSTEM_SERVER_CONFIG.SERVER_ID IS '서버아이디'; 
         COMMENT ON COLUMN TB_SYSTEM_SERVER_CONFIG.CONFIG_KEY IS '설정키'; 
         COMMENT ON COLUMN TB_SYSTEM_SERVER_CONFIG.CONFIG_VALUE IS '설정값'; 
         COMMENT ON COLUMN TB_SYSTEM_SERVER_CONFIG.EXPLAIN_DS IS '설명서술'; 
         COMMENT ON COLUMN TB_SYSTEM_SERVER_CONFIG.DEL_FG IS '삭제여부'; 
         COMMENT ON COLUMN TB_SYSTEM_SERVER_CONFIG.REG_FST_DT IS '최초등록일시'; 
         COMMENT ON COLUMN TB_SYSTEM_SERVER_CONFIG.UPT_LAST_DT IS '최종수정일시'; 
          


COMMIT;